//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMA_DEVEntities : DbContext
    {
        public BMA_DEVEntities()
            : base("name=BMA_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<BirthDetail> BirthDetails { get; set; }
        public virtual DbSet<BirthDetailAttachment> BirthDetailAttachments { get; set; }
        public virtual DbSet<BorisVesselMapping> BorisVesselMappings { get; set; }
        public virtual DbSet<BorisVesselStatusMapping> BorisVesselStatusMappings { get; set; }
        public virtual DbSet<BorisVesselSubTypeMapping> BorisVesselSubTypeMappings { get; set; }
        public virtual DbSet<BreachOfSecurity> BreachOfSecurities { get; set; }
        public virtual DbSet<BreachOfSecurityAttachment> BreachOfSecurityAttachments { get; set; }
        public virtual DbSet<ContactDetail> ContactDetails { get; set; }
        public virtual DbSet<ContactDetailAttachment> ContactDetailAttachments { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CrewDetail> CrewDetails { get; set; }
        public virtual DbSet<DeathDetail> DeathDetails { get; set; }
        public virtual DbSet<DeathDetailAttachment> DeathDetailAttachments { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<DiseaseAttachment> DiseaseAttachments { get; set; }
        public virtual DbSet<EnvironmentalDetail> EnvironmentalDetails { get; set; }
        public virtual DbSet<EnvironmentAttachment> EnvironmentAttachments { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<EventAction> EventActions { get; set; }
        public virtual DbSet<EventSeverity> EventSeverities { get; set; }
        public virtual DbSet<EventStatu> EventStatus { get; set; }
        public virtual DbSet<InjuryDetail> InjuryDetails { get; set; }
        public virtual DbSet<InjuryDetailAttachment> InjuryDetailAttachments { get; set; }
        public virtual DbSet<LookupData> LookupDatas { get; set; }
        public virtual DbSet<LookupType> LookupTypes { get; set; }
        public virtual DbSet<Marpol> Marpols { get; set; }
        public virtual DbSet<MarpolAttachment> MarpolAttachments { get; set; }
        public virtual DbSet<MaterialDamage> MaterialDamages { get; set; }
        public virtual DbSet<MaterialDamageAttachment> MaterialDamageAttachments { get; set; }
        public virtual DbSet<NearMissReport> NearMissReports { get; set; }
        public virtual DbSet<NearMissReportAttachment> NearMissReportAttachments { get; set; }
        public virtual DbSet<ObjectDetail> ObjectDetails { get; set; }
        public virtual DbSet<ObjectDetailAttachment> ObjectDetailAttachments { get; set; }
        public virtual DbSet<OtherVesselAttachment> OtherVesselAttachments { get; set; }
        public virtual DbSet<OtherVesselDetail> OtherVesselDetails { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<PersonalDetail> PersonalDetails { get; set; }
        public virtual DbSet<PersonalDetailAttachment> PersonalDetailAttachments { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<PersonnelActivation> PersonnelActivations { get; set; }
        public virtual DbSet<PersonnelRole> PersonnelRoles { get; set; }
        public virtual DbSet<PersonsRescuedAtSea> PersonsRescuedAtSeas { get; set; }
        public virtual DbSet<PersonsRescuedAtSeaAttachment> PersonsRescuedAtSeaAttachments { get; set; }
        public virtual DbSet<ReportableAdminAttachment> ReportableAdminAttachments { get; set; }
        public virtual DbSet<ReportableCategory> ReportableCategories { get; set; }
        public virtual DbSet<ReportableEvent> ReportableEvents { get; set; }
        public virtual DbSet<ReportableEventCorrespondence> ReportableEventCorrespondences { get; set; }
        public virtual DbSet<ReportableEventDetail> ReportableEventDetails { get; set; }
        public virtual DbSet<ReportableEventDetailHistory> ReportableEventDetailHistories { get; set; }
        public virtual DbSet<ReportableSubCategory> ReportableSubCategories { get; set; }
        public virtual DbSet<ReportableSubSubCategory> ReportableSubSubCategories { get; set; }
        public virtual DbSet<RescuedPersonDetail> RescuedPersonDetails { get; set; }
        public virtual DbSet<StowawayDetail> StowawayDetails { get; set; }
        public virtual DbSet<ThirdParty> ThirdParties { get; set; }
        public virtual DbSet<VesselDetail> VesselDetails { get; set; }
        public virtual DbSet<VesselInvolved> VesselInvolveds { get; set; }
        public virtual DbSet<VesselMissing> VesselMissings { get; set; }
        public virtual DbSet<VesselMissingAttachment> VesselMissingAttachments { get; set; }
        public virtual DbSet<BorisCompanyMapping> BorisCompanyMappings { get; set; }
        public virtual DbSet<ActionTaken> ActionTakens { get; set; }
        public virtual DbSet<ActionTakenAttachment> ActionTakenAttachments { get; set; }
    }
}
