//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorisCompanyMapping
    {
        public int id { get; set; }
        public string name { get; set; }
        public string contact { get; set; }
        public string imo { get; set; }
        public string account { get; set; }
        public string seafareremail { get; set; }
        public string defaultoperator { get; set; }
        public string url { get; set; }
    }
}
