//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorisVesselMapping
    {
        public int id { get; set; }
        public string name { get; set; }
        public string imo { get; set; }
        public string subtypeid { get; set; }
        public string companyid { get; set; }
        public string statusid { get; set; }
        public string anniversary { get; set; }
        public string officialno { get; set; }
        public string dpaname { get; set; }
        public string dpaemail { get; set; }
        public string dpatelephone { get; set; }
        public string dpafax { get; set; }
        public string ispscontactid { get; set; }
        public string csoname { get; set; }
        public string csotel { get; set; }
        public string csofax { get; set; }
        public string csoemail { get; set; }
        public string url { get; set; }
        public string surveyurl { get; set; }
        public string callsign { get; set; }
        public string yearofbuild { get; set; }
        public string lengthofvessel { get; set; }
        public string hullmaterial { get; set; }
        public string nettonnage { get; set; }
        public string grosstonnage { get; set; }
        public string mouldeddepth { get; set; }
        public string breadth { get; set; }
        public string wherebuilt { get; set; }
        public string mmsinumber { get; set; }
        public string vesselage { get; set; }
    }
}
