//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreachOfSecurity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BreachOfSecurity()
        {
            this.BreachOfSecurityAttachments = new HashSet<BreachOfSecurityAttachment>();
            this.StowawayDetails = new HashSet<StowawayDetail>();
        }
    
        public int BreachOfSecurityId { get; set; }
        public int ReportableEventId { get; set; }
        public string BoardingType { get; set; }
        public string LocationorAttemptedBoarding { get; set; }
        public string OwnVesselSpeed { get; set; }
        public string VesselFreeBoard { get; set; }
        public Nullable<int> NoOfPiratesArmed { get; set; }
        public string TypeofWeaponsObserved { get; set; }
        public string TypeOfWeaponsUsed { get; set; }
        public string IndividualApprehended { get; set; }
        public string LocalAuthoritiesInvolved { get; set; }
        public string AgencyContactDetails { get; set; }
        public string MethodOfBoarding { get; set; }
        public Nullable<int> NoOfPerson { get; set; }
        public string HidingPlaceOfStowaways { get; set; }
        public Nullable<System.DateTime> EmbarkationDate { get; set; }
        public string ExpectedPortOfDisembarkation { get; set; }
        public Nullable<System.DateTime> DisembarkationExpectedDate { get; set; }
        public Nullable<int> NumberOfFatalities { get; set; }
        public string StowawaysRequestingPoliticalAsylum { get; set; }
        public string StowayMethodOfBoarding { get; set; }
        public string FieldName { get; set; }
        public string UnAuthorizedIndividualApprehended { get; set; }
        public string UnAuthorizedLocalAuthoritiesInvolved { get; set; }
        public string UnAuthorizedAgencyContactDetails { get; set; }
        public string UnAuthorizedMethodofBoarding { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual ReportableEvent ReportableEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreachOfSecurityAttachment> BreachOfSecurityAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StowawayDetail> StowawayDetails { get; set; }
    }
}
