//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeathDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeathDetail()
        {
            this.DeathDetailAttachments = new HashSet<DeathDetailAttachment>();
        }
    
        public int DeathId { get; set; }
        public int ReportableEventId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string DiseasedPlace { get; set; }
        public string CauseOfDeath { get; set; }
        public string DeathCertifiedBy { get; set; }
        public string AnyUnderlyingConds { get; set; }
        public string UnderlyingReason { get; set; }
        public string NokName { get; set; }
        public string NokPhoneNumber { get; set; }
        public string NokAddress { get; set; }
        public Nullable<int> RelationShipId { get; set; }
        public string OtherRelation { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual ReportableEvent ReportableEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeathDetailAttachment> DeathDetailAttachments { get; set; }
    }
}
