//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventStatu()
        {
            this.ReportableEventDetails = new HashSet<ReportableEventDetail>();
        }
    
        public int EventStatusId { get; set; }
        public string EventStatus { get; set; }
        public Nullable<bool> IsNearMiss { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportableEventDetail> ReportableEventDetails { get; set; }
    }
}
