//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupData
    {
        public int LookupDataId { get; set; }
        public string LookupDataName { get; set; }
        public Nullable<int> LookupTypeId { get; set; }
        public bool IsSuppressed { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
    
        public virtual LookupType LookupType { get; set; }
    }
}
