//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int PassengerId { get; set; }
        public int PersonalDetailId { get; set; }
        public string PassengerName { get; set; }
        public string PassengerGender { get; set; }
        public string PassengerGenderOther { get; set; }
        public int PassengerNationalityId { get; set; }
        public int PassengerAge { get; set; }
        public string PassengerPassPortNumber { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
    
        public virtual PersonalDetail PersonalDetail { get; set; }
    }
}
