//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.ReportableEventDetails = new HashSet<ReportableEventDetail>();
        }
    
        public int PersonnelId { get; set; }
        public string PersonnelName { get; set; }
        public string PersonnelEmail { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> PersonnelRoleId { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedByPersonnelId { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> UpdatedByPersonnelId { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PersonnelRole PersonnelRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportableEventDetail> ReportableEventDetails { get; set; }
    }
}
