//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonnelRole()
        {
            this.Personnels = new HashSet<Personnel>();
        }
    
        public int PersonnelRoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
        public Nullable<int> CreatedByPersonnelId { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> UpdatedByPersonnelId { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personnel> Personnels { get; set; }
    }
}
