//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportableSubSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportableSubSubCategory()
        {
            this.ReportableEvents = new HashSet<ReportableEvent>();
        }
    
        public int ReportableSubSubCategoryId { get; set; }
        public Nullable<int> ReportableSubCategoryId { get; set; }
        public string ReportableSubSubCategoryName { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportableEvent> ReportableEvents { get; set; }
        public virtual ReportableSubCategory ReportableSubCategory { get; set; }
    }
}
