//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportableEventCorrespondence
    {
        public int ReportableEventRemarkId { get; set; }
        public Nullable<int> ReportableEventId { get; set; }
        public string Correspondence { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ReportableEvent ReportableEvent { get; set; }
    }
}
