//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class RescuedPersonDetail
    {
        public int RescuedPersonDetailId { get; set; }
        public int PersonsRescuedAtSeaId { get; set; }
        public string RescuedName { get; set; }
        public int RescuedPersonAge { get; set; }
        public string RescuedPersonGender { get; set; }
        public string RescuedGenderOther { get; set; }
        public int RescuedPersonNationalityId { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdateddBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PersonsRescuedAtSea PersonsRescuedAtSea { get; set; }
    }
}
