//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdParty
    {
        public int ThirdPartyId { get; set; }
        public int PersonalDetailId { get; set; }
        public string ThirdPartyName { get; set; }
        public string ThirdPartyGender { get; set; }
        public string ThirdPartyGenderOther { get; set; }
        public int ThidrPartyNationalityId { get; set; }
        public int ThirdPartyAge { get; set; }
        public string ThirdPartyPassPortNumber { get; set; }
        public string ThirdPartyOnDuty { get; set; }
        public string ThirdPartyRoleOnBoard { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
    
        public virtual PersonalDetail PersonalDetail { get; set; }
    }
}
