//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselInvolved
    {
        public int VesselInvolvedId { get; set; }
        public int OtherVesselDetailId { get; set; }
        public string VesselName { get; set; }
        public string ImoNumber { get; set; }
        public string FlagState { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
    
        public virtual OtherVesselDetail OtherVesselDetail { get; set; }
    }
}
