//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselMissing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VesselMissing()
        {
            this.VesselMissingAttachments = new HashSet<VesselMissingAttachment>();
        }
    
        public int VesselMissingId { get; set; }
        public int ReportableEventId { get; set; }
        public string LastKnownLatitudeDegree { get; set; }
        public string LastKnownLatitudeDecimal { get; set; }
        public string LastKnownLatitudeDirection { get; set; }
        public string LastKnownLongitudeDegree { get; set; }
        public string LastKnownLongitudeDecimal { get; set; }
        public string LastKnownLongitudeDirection { get; set; }
        public string LastKnownLocationTime { get; set; }
        public string LastKnownTimeZone { get; set; }
        public System.DateTime LastKnownPositionDate { get; set; }
        public int PositionSourceId { get; set; }
        public string OtherPositionSource { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual ReportableEvent ReportableEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VesselMissingAttachment> VesselMissingAttachments { get; set; }
    }
}
