//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselDetail
    {
        public int VesselDetailId { get; set; }
        public int ReportableEventId { get; set; }
        public string BriefDescription { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> CoastalstateId { get; set; }
        public Nullable<System.DateTime> DateofEvent { get; set; }
        public string Flag { get; set; }
        public string IMONumber { get; set; }
        public Nullable<bool> IsImoMatched { get; set; }
        public Nullable<bool> IsFatality { get; set; }
        public Nullable<bool> IsInjuredPerson { get; set; }
        public Nullable<bool> IsMaterialDamage { get; set; }
        public Nullable<bool> IsMissingPerson { get; set; }
        public Nullable<bool> IsPollution { get; set; }
        public string LatitudeDecimal { get; set; }
        public string LatitudeDegree { get; set; }
        public string LatitudeDirection { get; set; }
        public string LongitudeDecimal { get; set; }
        public string LongitudeDegree { get; set; }
        public string LongitudeDirection { get; set; }
        public Nullable<decimal> LengthOverAll { get; set; }
        public Nullable<bool> NotApplicable { get; set; }
        public Nullable<int> NoOfCrewOnBoard { get; set; }
        public Nullable<int> NoOfPasengers { get; set; }
        public Nullable<int> NoOfSuperNumeraries { get; set; }
        public string OperationofVesselId { get; set; }
        public Nullable<bool> PECHolder { get; set; }
        public Nullable<int> StageofPassageId { get; set; }
        public string ReportableTimeofEvent { get; set; }
        public string ReportableTimeZone { get; set; }
        public Nullable<bool> UnderPilotage { get; set; }
        public Nullable<int> VesselTypeId { get; set; }
        public string OtherVessel { get; set; }
        public string VoyageFrom { get; set; }
        public string VoyageTo { get; set; }
        public string VesselName { get; set; }
        public Nullable<bool> IsSuppressed { get; set; }
        public string OtherOperationVessel { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ReportableEvent ReportableEvent { get; set; }
    }
}
